# @package _global_
# defaults:
#   - data_manipulations: identity
#   - liftings: graph2simplicial_default

transforms:
  rewire:
    _target_: topobenchmarkx.transforms.data_transform.DataTransform
    transform_name: "RewireAFRC3"
    transform_type: "rewire the graph"
    loops: 5
  
  graph2simplicial_lifting:
    _target_: topobenchmarkx.transforms.data_transform.DataTransform
    transform_type: lifting
    transform_name: SimplicialCliqueLifting
    complex_dim: 3
    preserve_edge_attr: false
    signed: false
    feature_lifting: ProjectionSum

  