# @package _global_
# defaults:
#   - data_manipulations: identity
#   - liftings: graph2simplicial_default

transforms:
  rewire:
    _target_: topobenchmarkx.transforms.data_transform.DataTransform
    transform_name: "RewireAFRC3"
    transform_type: "rewire the graph"
    loops: 2

  