# @package _global_

transforms:
  keep_connected_component:
    _target_: topobenchmarkx.transforms.data_transform.DataTransform
    transform_name: "KeepOnlyConnectedComponent"
    transform_type: "data manipulation"
    num_components: 1